backend:
  name: Evolution Sim
  env: local

  server:
    host: "0.0.0.0"
    port: 8300
    allowedOrigins:
      - "http://localhost:5300"
      - "http://localhost"

  s3:
    port: 9000
    dataFolder: /localS3
