backend:
  appName: Evo Sim Service
  env: local

  server:
    host: "0.0.0.0"
    port: 8300
    allowedOrigins:
      - "http://localhost:5300"
      - "http://localhost"

    tokenGeneration:
      algorithm: HS256
      secret-key: NotReallyASecretSinceItsLocal

  encoding:
    byteLengths:
      creatureId: 2
      lifecycleSteps: 2
      gameboardSize: 2
    bitLengths:
      gameboard_integer: 3

  s3:
    port: 9000
    dataFolder: /localS3
