name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install python dependencies
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        python -c "import sys; print(sys.version)"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Test with pytest
      run: |
        pytest

    - name: Debug - Print Current Directory
      run: |
        cd testing-results
        pwd
        ls -la

    - name: Save test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: ./testing-results/coverage.xml

    - name: Save test results (complete folder)
      uses: actions/upload-artifact@v3
      with:
        name: Test Report Folder!
        path: testing-results/coverage.xml

