name: Python application

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: ["main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install python dependencies
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        python -c "import sys; print(sys.version)"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Lint with flake8
      run: |
        flake8 src
    - name: Test with pytest
      run: |
        pytest

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: backend/testing-results/coverage.xml
        junitxml-path: backend/testing-results/pytest.xml

    - name: Save test results fodler
      uses: actions/upload-artifact@v3
      with:
        name: test-report-folder
        path: backend/testing-results
