# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Test Cases
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set Python directory and print python version
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Lint with flake8
        run: |
          flake8 src
      - name: Test with pytest
        run: |
          pytest
      - name: Archive Folder
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: testing-results
